spring:
  application:
    name: Personalized-Study-Planner

  datasource:
    url: jdbc:postgresql://localhost:5432/personalized_study_planner
    username: java
    password: java

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8000