spring:
  application:
    name: Personalized-Study-Planner

  datasource:
    url: jdbc:postgresql://localhost:5432/study_planner
    username: java
    password: java

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5000 # changed to 8082, 8081 "was busy"
jwt:
  secret: 1zqnmqv2UgQ3Vk6nn53KeR+HnRjbhInN21Z2YsIQh5w= #secret key
  expiration: 3600000 # 1 hour in milliseconds